### ISSUE TITLE
missing babel-runtime/regenerator package on soya-next-cli

### ISSUE THREAD

**Issue by khaeransori** [traveloka/soya-next#1]
when I try to exec `soya-next-cli test-soya-next` there's an error described below
```
soya-next-cli test-soya-next
module.js:471
    throw err;
    ^

Error: Cannot find module 'babel-runtime/regenerator'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/khaer.ansori/.nvm/versions/node/v6.10.2/lib/node_modules/soya-next-cli/lib/index.js:3:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by sayuti-daniel** [comment]
Thanks for the report. You can simply upgrade `soya-next-cli` to `v0.1.5` to fix this issue.
